### ISSUE TITLE
bug: multicall on Infura WebSocket RPC fails on Deno

### ISSUE THREAD

**Issue by beeb** [wagmi-dev/viem#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.6.0

### Current Behavior

When calling the default `multicall` contract and using the `webSocket` transport to a Infura RPC, specifically when using Deno (1.36.0), the process crashes with the following:

```console
$ deno run --allow-net --allow-env --allow-read src/test.ts
Warning: Not implemented: ClientRequest.options.createConnection
error: Uncaught TypeError: Error parsing args at position 2: serde_v8 error: invalid type; expected: integer, got: undefined
    at Zlib.write (ext:deno_node/_zlib_binding.mjs:120:10)
    at DeflateRaw.Zlib._processChunk (ext:deno_node/_zlib.mjs:541:26)
    at DeflateRaw.Zlib._transform (ext:deno_node/_zlib.mjs:491:8)
    at DeflateRaw.Transform._write (ext:deno_node/_stream.mjs:4990:12)
    at doWrite (ext:deno_node/_stream.mjs:3963:16)
    at clearBuffer (ext:deno_node/_stream.mjs:4101:11)
    at onwrite (ext:deno_node/_stream.mjs:4000:11)
    at ext:deno_node/_stream.mjs:5003:11
    at Zlib.callback (ext:deno_node/_zlib.mjs:616:5)
    at ext:deno_node/_zlib_binding.mjs:132:14
```

This is specifically an issue linked to Deno and Infura on Websockets. Any other combination of runtime or RPC provider or transport does not cause an issue.

### Expected Behavior

However, if using an RPC server from Alchemy (also over websocket), the result is as expected:

```console
$ deno run --allow-net --allow-env --allow-read src/test.ts
Warning: Not implemented: ClientRequest.options.createConnection
[
  "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
]
```

Likewise, it works with both RPC providers on Node.js.

Likewise, it works on both runtimes for both RPC providers on HTTP.

### Steps To Reproduce

Here is the test script from above:

```ts
import { createPublicClient, parseAbi, webSocket } from 'npm:viem@1.6.0';
import { mainnet } from 'npm:viem@1.6.0/chains';

const UniPairAbi = parseAbi([
  'function token0() external view returns (address)',
  'function token1() external view returns (address)',
]);

const client = createPublicClient({
  chain: mainnet,
  transport: webSocket('YOUR_WSS_URI_HERE'),
});

const address = '0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc';

const data = await client.multicall({
  contracts: [
    {
      address,
      abi: UniPairAbi,
      functionName: 'token0',
    },
    {
      address,
      abi: UniPairAbi,
      functionName: 'token1',
    },
  ],
  allowFailure: false,
});

console.log(data);
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-ixq6yw?file=index.ts

**Comment by jxom** [comment]
Fixed in 1.15.5.
