### ISSUE TITLE
bug: `privateKeyToAccount` throws error in tests

### ISSUE THREAD

**Issue by 70nyIT** [wagmi-dev/viem#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.14

### Current Behavior

I'm creating a React plugin, to be later published on NPM, and I'm doing that with a test-driven approach. I'm encountering issues when using the function `privateKeyToAccount();` inside my test, and when the function is called I get the following error

 
```
   expected Uint8Array, got object

      42 |     const viewingPrivateKey = generatePrivateKey();
      43 |     console.log(viewingPrivateKey);
    > 44 |     const viewingAccount = privateKeyToAccount(viewingPrivateKey);
         |                                               ^
      45 |     const viewingPublicKey = viewingAccount.publicKey;
      46 |     const spendingPrivateKey = generatePrivateKey();
      47 |     const spendingAccount = privateKeyToAccount(spendingPrivateKey);

      at toBytes (node_modules/@noble/hashes/src/utils.ts:105:25)
      at hashC (node_modules/@noble/hashes/src/utils.ts:177:63)
      at keccak256 (node_modules/viem/utils/hash/keccak256.ts:19:27)
      at checksumAddress (node_modules/viem/utils/address/getAddress.ts:13:25)
      at publicKeyToAddress (node_modules/viem/accounts/utils/publicKeyToAddress.ts:16:25)
      at privateKeyToAccount (node_modules/viem/accounts/privateKeyToAccount.ts:20:37)
      at Object.<anonymous> (test/core/class/Client.test.ts:44:47)
```

### Expected Behavior

To ingest correctly the private key and return an object of type `Account`.

### Steps To Reproduce

Create a `projen` application with the following `.projenrc.ts`

```typescript
import { typescript } from 'projen';
import { NpmAccess, TypeScriptJsxMode } from 'projen/lib/javascript';

const project = new typescript.TypeScriptProject({
  defaultReleaseBranch: 'main',
  name: 'sdk',
  projenrcTs: true,
  releaseToNpm: true,

  // Npm publishing
  npmAccess: NpmAccess.PUBLIC,
  packageName: '@client/sdk',
  peerDeps: [
    'react@^16.8.0 || ^17.0.0 || ^18.0.0',
    'react-dom@^16.8.0 || ^17.0.0 || ^18.0.0',
  ],

  // Github repo
  gitignore: [
    '.idea',
  ],

  /* Dependencies */
  devDeps: [
    'jest-environment-jsdom@29.7.0',
    'react@^16.8.0',
    'react-dom@^16.8.0',
    '@types/react@^16.8.0',
    '@types/react-dom@^16.8.0',
    '@testing-library/jest-dom@^6.1.3',
    '@testing-library/react@^12.1.5',
    '@types/jest@^29.5.5',
  ],
  deps: [
    'viem@^1.10.14',
  ],

  /* Extending tsconfig to accept .tsx files and JSX */
  tsconfig: {
    compilerOptions: {
      jsx: TypeScriptJsxMode.REACT,
    },
    include: ['src/**/*.tsx'],
  },
  tsconfigDev: {
    compilerOptions: {
      jsx: TypeScriptJsxMode.REACT,
      esModuleInterop: true,
    },
    // need to set also the `test` folder, otherwise errors are raised when releasing the package with the github CI/CD
    include: ['src/**/*.tsx', 'test/**/*.tsx'],
  },

  /* Jest configuration extension */
  jestOptions: {
    jestConfig: {
      setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
      testEnvironment: 'jsdom',
      moduleNameMapper: {
        // point to the `react/jsx-runtime` bundled inside react NPM package without dealing with webpack or using create-react-app
        'react/jsx-runtime': '<rootDir>/node_modules/react',
        // same for `react-dom/client` as per `react/jsx-runtime`
        'react-dom/client': '<rootDir>/node_modules/react-dom',
      },
    },
  },
});

project.synth();
```

The `jest.setup.ts` file mentioned has the following structure

```typescript
import { TextEncoder } from 'util';

global.TextEncoder = TextEncoder;
```

then edit also the default test provided by projen with the following content

```typescript
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';

describe('Manual Key setup', () => {
  it('Pass generated keys and expect to be corrected', async () => {
    const viewingPrivateKey = generatePrivateKey();
    console.log(viewingPrivateKey);
    const viewingAccount = privateKeyToAccount(viewingPrivateKey);
    const viewingPublicKey = viewingAccount.publicKey;
    const spendingPrivateKey = generatePrivateKey();
    const spendingAccount = privateKeyToAccount(spendingPrivateKey);
    const spendingPublicKey = spendingAccount.publicKey;
    // other parts of the test here - not related to bug
  });
});
```

**Comment by tmm** [comment]
Mind packaging this up into a runnable example that reproduces the issue? Without this, it's less likely someone picks it up.

**Comment by jxom** [comment]
I'd assume this is something that needs tweaking in your test environment, and less so a bug in viem. Moving to discussion.
