### ISSUE TITLE
bug: Array index is out of bounds

### ISSUE THREAD

**Issue by kristoferlund** [wagmi-dev/viem#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.13.2

### Current Behavior

Getting ens avatar for `0x2d07D39E8463E3f05AE0B33D6d3D4012bC7f5d5E`/ `xdioz.robots.farm` causes out of bounds error.

```
Error: Slice starting at offset "5.9247327884235315e+75" is out-of-bounds (size: 228).

Version: viem@1.13.2
    at _0x3a68be._evaluate (https://viemgettingstartedvoazka-214a.w-credentialless.staticblitz.com/blitz.49a3680d.js:355:352403)
    at async ModuleJob.run (https://viemgettingstartedvoazka-214a.w-credentialless.staticblitz.com/blitz.49a3680d.js:181:2372) {
  details: undefined,
  docsPath: undefined,
  metaMessages: undefined,
  shortMessage: 'Slice starting at offset "5.9247327884235315e+75" is out-of-bounds (size: 228).',
  name: 'SliceOffsetOutOfBoundsError',
  version: 'viem@1.13.2'
}
```

### Expected Behavior

Expecting no error :)

### Steps To Reproduce

```javascript
import { createPublicClient, http } from 'viem';

import { mainnet } from 'viem/chains';
import { normalize } from 'viem/ens';

const publicClient = createPublicClient({
  chain: mainnet,
  transport: http(),
});

const address = '0x2d07D39E8463E3f05AE0B33D6d3D4012bC7f5d5E';

const ensName = await publicClient.getEnsName({
  address,
});

console.log('ensName', ensName);

if (ensName) {
  const ensAvatar = await publicClient.getEnsAvatar({
    name: normalize(ensName),
  });

  console.log('ensAvatar', ensAvatar);
}
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-voazka?file=index.js

**Comment by jxom** [comment]
When I try reproduce this, it seems that the Universal Resolver contract seems to be throwing a solidity panic error ([50/0x32 - Array index out of bounds](https://docs.soliditylang.org/en/v0.8.16/control-structures.html#panic-via-assert-and-error-via-require)). Any ideas on what would cause this @TateB?

**Comment by jxom** [comment]
After talking with ENS on this, it seems that the CCIP gateway server for `robots.farm` is giving back malformed 200 text responses instead of HTTP errors: https://stackblitz.com/edit/viem-getting-started-rbezhv?file=index.js. In this case, the CCIP gateway should have thrown a `415 - Unsupported Media Type`.

Might be best to get in touch with robots.farm to fix this on their end, but it seems that the root issue is that the avatar has an unsupported media type.
