### ISSUE TITLE
JSON Parse error watchBlocks/watchPendingTransactions onMessage 

### ISSUE THREAD

**Issue by unsphere** [wagmi-dev/viem#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.0

### Current Behavior

I get the following error for watchBlocks/onBlock and watchPendingTransactions/onTransactions using bun on my machine.

```
74 |             const requests = new Map();
75 |             // Set up a cache for subscriptions (eth_subscribe).
76 |             const subscriptions = new Map();
77 |             const onMessage = ({ data }) => {
79 |                 const message = JSON.parse(data);
                                    ^
SyntaxError: JSON Parse error: Unterminated string
      at onMessage (/node_modules/viem/_esm/utils/rpc.js:79:32)
      
74 |             const requests = new Map();
75 |             // Set up a cache for subscriptions (eth_subscribe).
76 |             const subscriptions = new Map();
77 |             const onMessage = ({ data }) => {
79 |                 const message = JSON.parse(data);
                                    ^
SyntaxError: JSON Parse error: Unexpected identifier "e3952934504e1559061048e8e53211abd9ab002cde0c87065024117847e20051181cab39540b08dde878137619"
      at onMessage (/node_modules/viem/_esm/utils/rpc.js:79:32)
```

When I add logging to the onMessage data in viem/_esm/utils/rpc.js I can see that the JSON body comes in chunks and therefore JSON cannot be parsed:

```
[2023-10-09T11:39:24.226Z] {"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xc6d972abf5b30d6f6e2028b31703b0a2","result":{"parentHash":"0x0c23fec689164a597feedba28bfcdeff668cbc5f8158c4bb0e83699ea3302f4c","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5","stateRoot":"0x4ed3457e5b7ea5688239118d235db36013e7195a0857f67bbfdfc1d5f285e183","transactionsRoot":"0xc5fe8398735dd60a320383737b2e5ad8c6f842d51a9796965178ceb44d3dfac6","receiptsRoot":"0x71264a58abc8d48c12360f1ae527ed5a800685987c23846d276d7ea582747e88","logsBloom":"0xf4aba143f38a25c410d888239e7d5c2973210064fb8ada8aa34bb8126c3977f29a4381d93349280042f7db647814158deb81c700ff086882b84617cc55bf3ad8e8eafc59540d89c92952d2abdec420e80d8600cc81c40e5a785b665e89fa2062522371ed932a487d215c77f149287f1d661828611a8ca6711651417c99edd3404a2c8fdc74ae5650016b79d003036977342f95718be984e8e2374acad535958e0f25c96236c9656843b226e09b93152ceff29070d090c28d80b9b0479088e2a055934c42b80544c019468f36046c8dd591f156
[2023-10-09T11:39:24.228Z] 065cbb3c370cc6f21e383462481034a6b9019026c89b8c1490f2653503c0ecb3b96f28805c74cdb50150c7d6d5","difficulty":"0x0","number":"0x1176de0","gasLimit":"0x1c9c380","gasUsed":"0xe378ae","timestamp":"0x6523e66b","extraData":"0x496c6c756d696e61746520446d6f63726174697a6520447374726962757465","mixHash":"0x03bee002f50d4d25fb2ed0af534cf4848590ab2fe1f8310b1d65431373012f50","nonce":"0x0000000000000000","baseFeePerGas":"0x1722daed1","withdrawalsRoot":"0x4f6747bf0782b01eddddc0aee14f891fafcffbbe895e246be839be862727f6ce","blobGasUsed":null,"excessBlobGas":null,"hash":"0x15fed8f7fa37fd7e3286b22a64e584426bfcee2d38f098c21a15c6c71c065c78"}}}
```

I tried several websocket URLs and viem versions, but the issue remains, so it must be something off with my machine because the linked codesandbox is working fine. Any idea?

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/fervent-archimedes-xhvdnd?file=%2Fblocks.ts%3A10%2C1

**Comment by jxom** [comment]
Seems to be working okay for me. Happy to take a look if you can provide a reproduction! Is Bun up to date, etc?
