### ISSUE TITLE
bug: Cannot destructure property 'id' of 'chain' as it is undefined.

### ISSUE THREAD

**Issue by alexbakers** [wagmi-dev/viem#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.24

### Current Behavior

```
TypeError: Cannot destructure property 'id' of 'chain' as it is undefined.
    at addChain (addChain.ts:13:11)
    at Object.addChain (wallet.ts:81:23)
    at Proxy.connectWallet (index.js?t=1680200284864:123:26)
    at Proxy.<anonymous> (pinia.mjs:1364:30)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (HomeView.vue:11:31)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:345:9)
```

id - 137

<img width="711" alt="image" src="https://user-images.githubusercontent.com/98721968/228930205-c5cbe475-c55e-4404-af12-4c5d65988e86.png">

### Expected Behavior

Add new chain

### Steps To Reproduce

```typescript
import {
  createWalletClient,
  custom
} from "viem";
import { polygon } from "viem/chains";

// ...

const walletClient = createWalletClient({
   chain: polygon,
   transport: custom(window.ethereum),
 });

 await walletClient.addChain(polygon);
```

**Comment by alexbakers** [comment]
Maybe the best solution would be without a parameter (like switchChain)?

`await walletClient.addChain(polygon);`
`await walletClient.switchChain(polygon);`

**Comment by jxom** [comment]
Looks like docs were out of date. Yeah, agree we should have same structure for `switchChain`. Open to a PR!
