### ISSUE TITLE
bug: walletClient writeContract gasPrice TransactionExecutionError

### ISSUE THREAD

**Issue by codingwithmanny** [wagmi-dev/viem#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.5

### Current Behavior

# Environment

- macos Ventura 13.1
- node v18.15.0
- pnpm v8.1.0

# Code

**File:** `./src/index.ts`

```ts
// Imports
// ========================================================
import { ZKThonContact } from './contract'; // Contract Address: 0x3aC587078b344a3d27e56632dFf236F1Aff04D56
import { createPublicClient, http, createWalletClient } from 'viem';
import { privateKeyToAccount } from 'viem/accounts' ;
import { polygonZkEvmTestnet } from 'viem/chains';
import dotenv from 'dotenv';

// Config
// ========================================================
dotenv.config();
const client = createPublicClient({
    chain: polygonZkEvmTestnet,
    transport: http(),
});

const account = privateKeyToAccount(`0x${process.env.WALLET_PRIVATE_KEY}`);
console.log({ address: account.address });

const walletClient = createWalletClient({
    account,
    chain: polygonZkEvmTestnet,
    transport: http(polygonZkEvmTestnet.rpcUrls.default.http[0]),
});


// Main Function
// ========================================================
(async () => {
    console.group('Main function');

    // Read from contract
    const getCurrentSubmission = await client.readContract({
        ...ZKThonContact,
        functionName: 'getCurrentSubmission'
    });
    console.log({ getCurrentSubmission });

    // Write to contract
    const { request } = await client.simulateContract({
        ...ZKThonContact,
        functionName: 'submitUsername',
        account,
        args: ['codingwithmanny']
    });
    const hash = await walletClient.writeContract(request);
    console.log({ hash });
    
    console.groupEnd();
})();
```

# Running Script

```bash
# FROM ./

./node_modules/.bin/ts-node src/index.ts;

# Output:
# { address: '0xSomeWalletAddress' }
# Main function
#   { getCurrentSubmission: 'samirmerhar' }
#   /Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/utils/errors/getTransactionError.ts:19
#     return new TransactionExecutionError(cause, {
#            ^
#   TransactionExecutionError: `gasPrice` is not a valid EIP-1559 Transaction attribute.
#   
#   Request Arguments:
#     from:  0xSomeWalletAddress
#     to:    0x3aC587078b344a3d27e56632dFf236F1Aff04D56
#     data:  0x70020c040000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f636f64696e67776974686d616e6e790000000000000000000000000000000000
#   
#   Version: viem@0.2.5
#       at getTransactionError (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/utils/errors/getTransactionError.ts:19:10)
#       at sendTransaction (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/actions/wallet/sendTransaction.ts:139:11)
#       at processTicksAndRejections (node:internal/process/task_queues:95:5)
#       at async writeContract (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/actions/wallet/writeContract.ts:61:16) {
#     details: undefined,
#     docsPath: undefined,
#     metaMessages: [
#       'Request Arguments:',
#       '  from:  0xSomeWalletAddress\n' +
#         '  to:    0x3aC587078b344a3d27e56632dFf236F1Aff04D56\n' +
#         '  data:  0x70020c040000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f636f64696e67776974686d616e6e790000000000000000000000000000000000'
#     ],
#     shortMessage: '`gasPrice` is not a valid EIP-1559 Transaction attribute.',
#     cause: BaseError [ViemError]: `gasPrice` is not a valid EIP-1559 Transaction attribute.
#     
#     Version: viem@0.2.5
#         at assertTransactionEIP1559 (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/utils/transaction/assertTransaction.ts:23:11)
#         at serializeTransactionEIP1559 (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/utils/transaction/serializeTransaction.ts:78:3)
#         at serializeTransaction (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/utils/transaction/serializeTransaction.ts:45:12)
#         at signTransaction (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/accounts/utils/signTransaction.ts:34:54)
#         at Object.signTransaction (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/accounts/privateKeyToAccount.ts:29:14)
#         at sendTransaction (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/actions/wallet/sendTransaction.ts:104:44)
#         at processTicksAndRejections (node:internal/process/task_queues:95:5)
#         at async writeContract (/Users/username/path/to/node_modules/.pnpm/viem@0.2.5_typescript@5.0.3/node_modules/viem/src/actions/wallet/writeContract.ts:61:16) {
#       details: undefined,
#       docsPath: undefined,
#       metaMessages: undefined,
#       shortMessage: '`gasPrice` is not a valid EIP-1559 Transaction attribute.'
#     }
#   }
#  ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

No errors and a successful transaction hash returned.

### Steps To Reproduce

See Current Behavior for steps.

**Comment by fubhy** [comment]
What does `ZKThonContact` contain? Is there a `gasPrice` property in there that you are spreading into the `simulateContract` call?
