### ISSUE TITLE
bug: `watchPendingTransactions` error "Method not supported"

### ISSUE THREAD

**Issue by codeonblocks** [wagmi-dev/viem#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.26

### Current Behavior

Whenever I try to call the `watchPendingTransactions` it gives me an error I pasted below.

Code that produces error:
```typescript
import { createPublicClient, http } from 'viem';
import { mainnet } from 'viem/chains';

const publicClient = createPublicClient({
  chain: mainnet,
  transport: http()
});

const unwatch = publicClient.watchPendingTransactions({ 
  onTransactions: hashes => console.log(hashes),
  onError: err => console.error(err) 
})
```

Error:
```bash
MethodNotSupportedRpcError: Method is not implemented.

URL: https://cloudflare-eth.com
Request body: {"method":"eth_newPendingTransactionFilter"}

Details: Method not supported
Version: viem@0.3.26
    at delay.count.count (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/utils/buildRequest.ts:82:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/utils/promise/withRetry.ts:34:22) {
  details: 'Method not supported',
  docsPath: undefined,
  metaMessages: [
    'URL: https://cloudflare-eth.com',
    'Request body: {"method":"eth_newPendingTransactionFilter"}'
  ],
  shortMessage: 'Method is not implemented.',
  version: 'viem@0.3.26',
  cause: RpcRequestError: RPC Request failed.
  
  URL: https://cloudflare-eth.com
  Request body: {"method":"eth_newPendingTransactionFilter"}
  
  Details: Method not supported
  Version: viem@0.3.26
      at Object.http (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/utils/rpc.ts:111:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at request (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/clients/transports/http.ts:59:30)
      at delay.count.count (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/utils/buildRequest.ts:67:18)
      at attemptRetry (/home/adrian/Documents/Projects/blockchain-wallet/tx-server/node_modules/viem/src/utils/promise/withRetry.ts:34:22) {
    details: 'Method not supported',
    docsPath: undefined,
    metaMessages: [
      'URL: https://cloudflare-eth.com',
      'Request body: {"method":"eth_newPendingTransactionFilter"}'
    ],
    shortMessage: 'RPC Request failed.',
    version: 'viem@0.3.26',
    cause: { code: -32042, message: 'Method not supported' },
    code: -32042
  },
  code: -32042
}
```

### Expected Behavior

It should give me the pending transactions like the docs say.

### Steps To Reproduce

Copy and paste the code I provided.

### Anything else?
**OS Info**
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11

`package.json`:

```json
{
  "name": "tx-server",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node ./build/src/index.js",
    "dev": "export NODE_ENV=development && ts-node-dev --ignore-watch typechain-types --respawn --pretty --transpile-only src/index.ts",
    "build": "tsc -p .",
    "lint": "eslint .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC",
  "devDependencies": {
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "@types/morgan": "^1.9.4",
    "@types/node": "^20.1.7",
    "eslint": "^8.40.0",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "morgan": "^1.10.0",
    "viem": "^0.3.26"
  }
}

```

**Comment by jxom** [comment]
Unfortunately, not all RPC Providers support `eth_newPendingTransactionFilter`, including Cloudflare (your example). Might be best to find one that does support it, like Alchemy, Ankr, QuikNode, or Infura.

**Comment by codeonblocks** [comment]
> Unfortunately, not all RPC Providers support `eth_newPendingTransactionFilter`, including Cloudflare (your example). Might be best to find one that does support it, like Alchemy, Ankr, QuikNode, or Infura.

I'm using the exact code snippet from the documentation the viem website provides though. If the provided Urls don't support the method, I Believe the docs should be changed to reflect that or have a note somewhere to let the user know so that they don't get stuck for an hour trying to debug lol
