### ISSUE TITLE
bug: viem doesn't run on Vercel Edge Functions

### ISSUE THREAD

**Issue by johanneskares** [wagmi-dev/viem#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.36

### Current Behavior

I import a function from viem into a file, compiled for vercel's edge runtime

### Expected Behavior

The build completes

### Steps To Reproduce

1. open the codesandbox link.
2. npm run build

The build fails with this error:

```
node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:28:395974
    at Hook.eval [as callAsync] (eval at create (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
    at Object.processResource (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:28:395899)
    at processResource (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
    at runLoaders (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
    at NormalModule._doBuild (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:28:395761)
    at NormalModule.build (/project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:28:397789)
    at /project/home/johanneskares/workspace/node_modules/next/dist/compiled/webpack/bundle5.js:28:81243

Import trace for requested module:
node:crypto
./node_modules/@noble/hashes/esm/cryptoNode.js
./node_modules/@noble/hashes/esm/utils.js
./node_modules/@noble/hashes/esm/sha3.js
./node_modules/viem/dist/esm/utils/hash/keccak256.js
./node_modules/viem/dist/esm/index.js
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/crazy-dawn-y5cfuf

**Comment by tmm** [comment]
Can check out [this thread](https://github.com/wagmi-dev/viem/discussions/368#discussioncomment-5902124) to get unblocked.

**Comment by fubhy** [comment]
Check out this in particular: https://github.com/jxom/viem-nextjs-edge

**Comment by johanneskares** [comment]
Great, thanks for the hints. I added the patch. It's working now.
