### ISSUE TITLE
bug: TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by chrehman** [wagmi-dev/viem#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.36

### Current Behavior

This error i am receiving when i am trying to read smart contract variable using useContractRead wagmi hook.

Docs: https://viem.sh/docs/contract/readContract.html
Details: Cannot convert a BigInt value to a number
Version: viem@0.3.36
    at pe (getContractError.ts:55:10)
    at readContract.ts:100:11
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.throw (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)

**Comment by tmm** [comment]
See https://github.com/wagmi-dev/viem/issues/564 or add a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using [new.viem.sh](https://new.viem.sh).
