### ISSUE TITLE
bug: usePrepareContractWrite is throwing "ContractFunctionExecutionError: Execution reverted for an unknown reason."

### ISSUE THREAD

**Issue by j-5-s** [wagmi-dev/viem#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.37

### Current Behavior

im calling:
```js
const {
    config,
  } = usePrepareContractWrite({
    address: "0x84e13e64b79533c9a2d89d378d07dd382b2ef74f",
    abi: cloneableContract.abi,
    functionName: "mintOriginalNFT",
    args: ["ipfs://QmacZsryYxwknCoL3uziSF4coeJ4cyKFaXmrjbaLo5sCTY"],
  });
  ```
  however its throwing:
  ```
  next-dev.js:20 ContractFunctionExecutionError: Execution reverted for an unknown reason.

Raw Call Arguments:
  from:  0x66c2801e144A0BA4d7F6aFF62f535F312aaF609a
  to:    0x84e13e64b79533c9a2d89d378d07dd382b2ef74f
  data:  0xd80638a700000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d61635a7372795978776b6e436f4c33757a69534634636f654a3463794b4661586d726a62614c6f35734354590000000000000000000000
 
Contract Call:
  address:   0x84e13e64b79533c9a2d89d378d07dd382b2ef74f
  function:  mintOriginalNFT(string _tokenURI)
  args:                     (ipfs://QmacZsryYxwknCoL3uziSF4coeJ4cyKFaXmrjbaLo5sCTY)
  sender:    0x66c2801e144A0BA4d7F6aFF62f535F312aaF609a

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: execution reverted
Version: viem@0.3.37
    at getContractError (getContractError.js:24:1)
    at simulateContract (simulateContract.js:40:31)
    at async prepareWriteContract (chunk-OKULXQAF.js:2078:29)
```

### Expected Behavior

it should not throw

### Steps To Reproduce

call the contract as shown above

### Anything else?

Here is the api and contract:
```sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract CloneableNFT is ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    uint256 private _defaultClonePrice = 0.01 ether;
    mapping(uint256 => bool) private _isClone;
    mapping(uint256 => uint256) private _cloneOf;
    mapping(uint256 => uint256) private _clonePrice;

    constructor(string memory name, string memory symbol) ERC721(name, symbol) {
    }

    function mintOriginalNFT(string memory _tokenURI) public onlyOwner {
        _tokenIdCounter.increment();
        uint256 newTokenId = _tokenIdCounter.current();
        _mint(msg.sender, newTokenId);
        _isClone[newTokenId] = false;
        _setTokenURI(newTokenId, _tokenURI);
    }

    function mintClone(uint256 tokenId) public payable {
        require(_exists(tokenId), "Invalid token ID");
        require(!_isClone[tokenId], "Cannot clone a clone");
        uint256 clonePrice = _clonePrice[tokenId] > 0 ? _clonePrice[tokenId] : _defaultClonePrice;
        require(msg.value >= clonePrice, "Insufficient funds to mint clone");

        _tokenIdCounter.increment();
        uint256 newTokenId = _tokenIdCounter.current();
        _safeMint(msg.sender, newTokenId);
        _isClone[newTokenId] = true;
        _cloneOf[newTokenId] = tokenId;
    }

    function isClone(uint256 tokenId) public view returns (bool) {
        return _isClone[tokenId];
    }

    function getOriginal(uint256 tokenId) public view returns (uint256) {
        require(_isClone[tokenId], "Token is not a clone");
        return _cloneOf[tokenId];
    }

    function setClonePrice(uint256 tokenId, uint256 newPrice) public onlyOwner {
        _clonePrice[tokenId] = newPrice;
    }

    function getDefaultClonePrice() public view returns (uint256) {
        return _defaultClonePrice;
    }

    function setDefaultClonePrice(uint256 newPrice) public onlyOwner {
        _defaultClonePrice = newPrice;
    }

    function _burn(uint256 tokenId) internal override(ERC721URIStorage) {
        super._burn(tokenId);
    }

    function tokenURI(uint256 tokenId) public view override(ERC721URIStorage) returns (string memory) {
        return super.tokenURI(tokenId);
    }

    function withdraw() public onlyOwner {
        payable(owner()).transfer(address(this).balance);
    }
}

```
[CloneableContract.json.zip](https://github.com/wagmi-dev/viem/files/11579923/CloneableContract.json.zip)

**Comment by j-5-s** [comment]
sorry, i dont think the deployed contract was the contract i had posted above.

**Comment by j-5-s** [comment]
@milaabl my issue was because the abi did not match the deployed contract.

**Comment by milaabl** [comment]
> @milaabl my issue was because the abi did not match the deployed contract.

Thanks a bunch! Appreciate your answer :)
