### ISSUE TITLE
bug: Passing websocket transport fails

### ISSUE THREAD

**Issue by crystalin** [wagmi-dev/viem#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.40

### Current Behavior

```
Version: viem@0.3.40
    at getTransactionError (myproject/node_modules/viem/src/utils/errors/getTransactionError.ts:22:10)
    at sendTransaction (myproject/node_modules/viem/src/actions/wallet/sendTransaction.ts:184:30)
    at async main (myproject/src/tools/list-precompiles.ts:226:22) {
  details: 'The "url" argument must be of type string. Received an instance of URL',
  docsPath: undefined,
  shortMessage: 'An unknown RPC error occurred.',
  version: 'viem@0.3.40',
  cause: UnknownRpcError: An unknown RPC error occurred.
  
  Details: The "url" argument must be of type string. Received an instance of URL
  Version: viem@0.3.40
      at delay.count.count (myproject/node_modules/viem/src/utils/buildRequest.ts:94:17)
      at async attemptRetry (myproject/node_modules/viem/src/utils/promise/withRetry.ts:34:22) {
    details: 'The "url" argument must be of type string. Received an instance of URL',
    docsPath: undefined,
    metaMessages: undefined,
    shortMessage: 'An unknown RPC error occurred.',
    version: 'viem@0.3.40',
    cause: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of URL
        at new NodeError (node:internal/errors:399:5)
        at validateString (node:internal/validators:163:11)
        at Url.parse (node:url:195:3)
        at Object.urlParse [as parse] (node:url:166:13)
        at WebSocket.initAsClient (myproject/node_modules/ws/lib/WebSocket.js:534:25)
        at new WebSocket (myproject/node_modules/ws/lib/WebSocket.js:72:20)
        at fn (myproject/node_modules/viem/src/utils/rpc.ts:165:25) {
      code: 'ERR_INVALID_ARG_TYPE'
    },
    code: -1
  }
}
```

### Expected Behavior

It should be able to send the transaction

### Steps To Reproduce

```
const abiItem = {
  inputs: [{ internalType: "address", name: "a", type: "address" }],
  name: "updateAccountCode",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
};


const account = privateKeyToAccount("0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133");
const wallet = createWalletClient({
  transport: webSocket("wss://fork.alphanet.kaki.dev"),
  account,
  chain: localhost,
});
  
const data = encodeFunctionData({
  abi: [abiItem],
  functionName: 'updateAccountCode', 
  args: ['0x0000000000000000000000000000000000000009']
})
const hash = await wallet.sendTransaction({
  chain: viem.chain,
  account,
  to: '0x0000000000000000000000000000000000000815',
  data,
})
```

### Anything else?

The code seems to convert the url to URL there: https://github.com/wagmi-dev/viem/blob/23d74066f9ec81205b4f0907b31d3c9121765c82/src/utils/rpc.ts#L142
and after uses it to call websocket(url) there: https://github.com/wagmi-dev/viem/blob/23d74066f9ec81205b4f0907b31d3c9121765c82/src/utils/rpc.ts#L165

**Comment by crystalin** [comment]
Probably changing 
```
const webSocket = new WebSocket(url) 
```
to 
```
const webSocket = new WebSocket(urlKey) 
```
should work

**Comment by jxom** [comment]
Seems to work for me: https://stackblitz.com/edit/github-19zwgs?file=index.ts (replace <API_KEY> with Alchemy API Key).

What runtime are you using? Browser, Node, Deno, Bun, etc?

**Comment by crystalin** [comment]
Node v20.1.0

**Comment by crystalin** [comment]
According to the doc of https://github.com/heineiuo/isomorphic-ws#readme it uses [ws](https://github.com/websockets/ws) or native [Websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) which both seem to take url as a string

**Comment by jxom** [comment]
Interesting. I believe they also accept a URL object. Wonder what's going on there.

**Comment by crystalin** [comment]
I checked the dependency and it is using "ws" 3.3.3 which is from 2017 and doesn't support URL.
I think you need to update some libraries (maybe ismorphic-ws) to have a more recent one

**Comment by crystalin** [comment]
Sorry it is my bad, the ws was somehow deduped and used a older dependency from another library ("web3")
