### ISSUE TITLE
bug: InvalidAddressError: Address "[object Object]" is invalid.

### ISSUE THREAD

**Issue by dapjeongneo** [wagmi-dev/viem#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

Hi team, I am trying to estimate gas for a transaction. But I'm running into a weird error, i tried to verify my addresses were valid using `isAddress`. Thanks for helping out.

```
const publicClient = createPublicClient({
  chain: zkSyncTestnet,
  transport: http(),
})

const { data } = useQuery({
    queryKey: [userAddress],
    queryFn: async () => {
      const ret = publicClient.estimateContractGas({
        address: contractAddress,
        abi: myAbi,
        functionName: "swapExactTokensForTokens",
        args: [
          0,
          0,
          [token1, token2],
          userAddress,
          100000000000000,
        ],
        account: userAddress,
      })
    },
  })
```

estimating contract gas is returning `InvalidAddressError: Address "[object Object]" is invalid.`

### Expected Behavior

Should return the estimated gas

### Anything else?

```
InvalidAddressError: Address "[object Object]" is invalid.

Version: viem@1.0.7
    at encodeAddress (encodeAbiParameters.js:98:1)
    at prepareParam (encodeAbiParameters.js:47:1)
    at encodeArray (encodeAbiParameters.js:114:1)
    at prepareParam (encodeAbiParameters.js:39:1)
    at prepareParams (encodeAbiParameters.js:31:1)
    at encodeAbiParameters (encodeAbiParameters.js:19:1)
    at encodeFunctionData (encodeFunctionData.js:27:30)
    at estimateContractGas (estimateContractGas.js:33:36)
```

**Comment by dapjeongneo** [comment]
sorry guys, i found the typo. please ignore me.
