### ISSUE TITLE
Method "watchAsset" in "walletClient" does not work

### ISSUE THREAD

**Issue by toufique-imam** [wagmi-dev/viem#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.12

### Current Behavior

calling  walletClient.watchAsset function giving error.
```
Error while adding token type 1: MethodNotFoundRpcError: The method does not exist / is not available.

Details: the method wallet_watchAsset does not exist/is not available
Version: viem@1.2.12
    at delay.count.count (buildRequest.js:29:1)
    at async attemptRetry (withRetry.js:27:1)
```

### Expected Behavior

A window to show up in the wallet to add the token in the wallet.

### Steps To Reproduce

click connect wallet then use any mobile wallet (metamask, zerion etc.)
```js

import { useEffect } from "react";
import { useToken, useWalletClient } from 'wagmi';

const TOKEN_CONTRACT_ADDRESS = '0x2170Ed0880ac9A755fd29B2688956BD959F933F8';
export const Header = () => {
    const { data: walletClient } = useWalletClient({
        onSettled(data, error) {
            if (error) {
                console.error("useWalletClient", error)
            } else {
                console.log("useWalletClient", data)
                addFriendTokenInAsset();
            }
        }
    })
    const tokenData = useToken({
        address: TOKEN_CONTRACT_ADDRESS
    })

    const addTokenInWallet = async (token) => {
        await walletClient.watchAsset(token).then((success) => {
            if (success) {
                console.log("Successfully added Token to Wallet!");
                return true;
            } else {
                throw new Error("Adding assets to wallet went wrong.");
            }
        }).catch((error) => {
            throw error;
        });
    }

    const addFriendTokenInAsset = async () => {
        tokenData.refetch().then(() => {
            const token = {
                type: "ERC20",
                options: {
                    address: TOKEN_CONTRACT_ADDRESS,
                    symbol: tokenData.data.name,
                    decimals: tokenData.data.decimals,
                    image: "https://i.imgur.com/WZlfch1.png",
                },
            };
            addTokenInWallet(token)
                .then(() => {
                    console.log("Added token type 1");
                })
                .catch((error) => {
                    console.error('Error while adding token type 1:', error);
                });
        }).catch((error) => {
            console.error('Error while getting token name:', error);
        });
    }


    useEffect(() => {
    }, []);

    return (
        <>
            <div>
                <Web3Button showBalance={false} chainStatus='icon' accountStatus={'avatar'} />
            </div>
        </>
    );
};
```
this code along with the default setup of walletconnect with wagmi

**Comment by jxom** [comment]
As the error mentions, most mobile wallets do not support `wallet_watchAsset`. I am unsure of a mobile wallet that does. This is more common in extension wallets.

**Comment by toufique-imam** [comment]
@jxom can you tell me what can be done in that situation without user manually adding the token

**Comment by jxom** [comment]
Nothing really, unfortunately. It’s out of our control. 😔
