### ISSUE TITLE
bug: ContractFunctionExecutionError

### ISSUE THREAD

**Issue by pablohpsilva-forjnetwork** [wagmi-dev/viem#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.1

### Current Behavior
```
ContractFunctionExecutionError: The contract function "tiers" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "tiers",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
 
Contract Call:
  address:   0x862afDb5BEF06BC673a23E9cB2109d55125c3069
  function:  tiers(uint256)
  args:           (3)

Docs: https://viem.sh/docs/contract/multicall.html
Version: viem@1.4.1
    at getContractError (webpack-internal:///../../node_modules/viem/dist/esm/utils/errors/getContractError.js:31:12)
    at eval (webpack-internal:///../../node_modules/viem/dist/esm/actions/public/multicall.js:150:110)
    at Array.map (<anonymous>)
    at multicall (webpack-internal:///../../node_modules/viem/dist/esm/actions/public/multicall.js:132:27)
    at async Promise.all (index 0)
    at async readContracts (webpack-internal:///../../node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js:2252:31)
```

### Expected Behavior

It should simply call the contract and return the data

### Steps To Reproduce

You can test the contract [here](https://sepolia.etherscan.io/address/0x862afDb5BEF06BC673a23E9cB2109d55125c3069#readContract) via the `tiers` method using the arg `2`

Simply use react + wagmi + viem (**sepolia** network):
```
const { data } = useContractRead({
    functionName: "tiers",
    args: [2],
    address: "0x862afDb5BEF06BC673a23E9cB2109d55125c3069",
    abi: [
    {
        "name": "AlreadyInitialized",
        "type": "error",
        "inputs": []
    },
    {
        "name": "ArrayLengthsDiffer",
        "type": "error",
        "inputs": []
    },
    {
        "name": "BaseURINotSet",
        "type": "error",
        "inputs": []
    },
    {
        "name": "ClaimPeriodTooShort",
        "type": "error",
        "inputs": []
    },
    {
        "name": "CurrentlyNotClaimPeriod",
        "type": "error",
        "inputs": []
    },
    {
        "name": "IncorrectAddress",
        "type": "error",
        "inputs": []
    },
    {
        "name": "InsufficientBalance",
        "type": "error",
        "inputs": []
    },
    {
        "name": "InvalidPartnerSharePct",
        "type": "error",
        "inputs": []
    },
    {
        "name": "InvalidPartnerWallet",
        "type": "error",
        "inputs": []
    },
    {
        "name": "InvalidProof",
        "type": "error",
        "inputs": []
    },
    {
        "name": "MaxSupplyReached",
        "type": "error",
        "inputs": []
    },
    {
        "name": "MintLimitReached",
        "type": "error",
        "inputs": []
    },
    {
        "name": "MsgSenderIsNotOwner",
        "type": "error",
        "inputs": []
    },
    {
        "name": "NoConfirmedIds",
        "type": "error",
        "inputs": []
    },
    {
        "name": "OperatorNotAllowed",
        "type": "error",
        "inputs": [
            {
                "name": "operator",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "name": "PartnerActive",
        "type": "error",
        "inputs": []
    },
    {
        "name": "PartnerAlreadyExists",
        "type": "error",
        "inputs": []
    },
    {
        "name": "PartnerDeactivated",
        "type": "error",
        "inputs": []
    },
    {
        "name": "PartnerNotFound",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TierLengthTooShort",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TierNumberIncorrect",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TierPeriodHasEnded",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TierPeriodHasntStarted",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TokenIsSoulbound",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TokenNotAcceptedAsPayment",
        "type": "error",
        "inputs": []
    },
    {
        "name": "TotalSupplyGreaterThanMaxSupply",
        "type": "error",
        "inputs": []
    },
    {
        "name": "ApprovalForAll",
        "type": "event",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "operator",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "approved",
                "type": "bool",
                "indexed": false,
                "internalType": "bool"
            }
        ],
        "anonymous": false
    },
    {
        "name": "BatchMint",
        "type": "event",
        "inputs": [
            {
                "name": "user",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "_ids",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            },
            {
                "name": "_amounts",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            }
        ],
        "anonymous": false
    },
    {
        "name": "OwnershipTransferred",
        "type": "event",
        "inputs": [
            {
                "name": "previousOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "newOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "name": "TierMint",
        "type": "event",
        "inputs": [
            {
                "name": "user",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "_tier",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "_ids",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            },
            {
                "name": "_amounts",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            }
        ],
        "anonymous": false
    },
    {
        "name": "TokenBurn",
        "type": "event",
        "inputs": [
            {
                "name": "_tokenIds",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            },
            {
                "name": "_amounts",
                "type": "uint256[]",
                "indexed": true,
                "internalType": "uint256[]"
            },
            {
                "name": "_user",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "name": "TransferBatch",
        "type": "event",
        "inputs": [
            {
                "name": "operator",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "from",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "to",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "ids",
                "type": "uint256[]",
                "indexed": false,
                "internalType": "uint256[]"
            },
            {
                "name": "values",
                "type": "uint256[]",
                "indexed": false,
                "internalType": "uint256[]"
            }
        ],
        "anonymous": false
    },
    {
        "name": "TransferSingle",
        "type": "event",
        "inputs": [
            {
                "name": "operator",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "from",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "to",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "id",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "value",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "name": "URI",
        "type": "event",
        "inputs": [
            {
                "name": "value",
                "type": "string",
                "indexed": false,
                "internalType": "string"
            },
            {
                "name": "id",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "name": "OPERATOR_FILTER_REGISTRY",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "contract IOperatorFilterRegistry"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "acceptedTokenPrice",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "amountCalc",
        "type": "function",
        "inputs": [
            {
                "name": "_amounts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "availableIdsForTierNumber",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "balanceOf",
        "type": "function",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "id",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "balanceOfBatch",
        "type": "function",
        "inputs": [
            {
                "name": "accounts",
                "type": "address[]",
                "internalType": "address[]"
            },
            {
                "name": "ids",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "baseURI",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "batchMint",
        "type": "function",
        "inputs": [
            {
                "name": "to",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "ids",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "amounts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "burn",
        "type": "function",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "id",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "burnBatch",
        "type": "function",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "ids",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "amounts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "collectTreasury",
        "type": "function",
        "inputs": [
            {
                "name": "_token",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "emergencyPause",
        "type": "function",
        "inputs": [
            {
                "name": "_paused",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "erc1155Initialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "getAvailableIdsForTierNumber",
        "type": "function",
        "inputs": [
            {
                "name": "_tierNumber",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "initialize",
        "type": "function",
        "inputs": [
            {
                "name": "_multisig",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "_treasuryWallet",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "_baseURI",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "_name",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "_symbol",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "_mintFee",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "_saleId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "tiersNumbers",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "limitPerWalletPerTier",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "starts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "ends",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "merkleRoots",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
            },
            {
                "name": "isTierPublic",
                "type": "bool[]",
                "internalType": "bool[]"
            },
            {
                "name": "idsAvailable",
                "type": "uint256[][]",
                "internalType": "uint256[][]"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "initialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "isAdmin",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "isApprovedForAll",
        "type": "function",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "operator",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "mintFee",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "mintedPerAddress",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "modifiersInitialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "multisig",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "name",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "owner",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "paused",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "paymentInitialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "removePaymentToken",
        "type": "function",
        "inputs": [
            {
                "name": "_token",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "renounceOwnership",
        "type": "function",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "safeBatchTransferFrom",
        "type": "function",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "to",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "tokenIds",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "amounts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "safeTransferFrom",
        "type": "function",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "to",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "tokenId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "amount",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "saleId",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "setAdmin",
        "type": "function",
        "inputs": [
            {
                "name": "_admin",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "_isAdmin",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setApprovalForAll",
        "type": "function",
        "inputs": [
            {
                "name": "operator",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "approved",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setBaseURI",
        "type": "function",
        "inputs": [
            {
                "name": "_baseURI",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setMintFee",
        "type": "function",
        "inputs": [
            {
                "name": "_mintFee",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setMultiSig",
        "type": "function",
        "inputs": [
            {
                "name": "_multisig",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setName",
        "type": "function",
        "inputs": [
            {
                "name": "_name",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setNewSaleInfo",
        "type": "function",
        "inputs": [
            {
                "name": "tiersNumbers",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "limitPerWalletPerTier",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "starts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "ends",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "merkleRoots",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
            },
            {
                "name": "isTierPublic",
                "type": "bool[]",
                "internalType": "bool[]"
            },
            {
                "name": "idsAvailable",
                "type": "uint256[][]",
                "internalType": "uint256[][]"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setPayments",
        "type": "function",
        "inputs": [
            {
                "name": "_tokens",
                "type": "address[]",
                "internalType": "address[]"
            },
            {
                "name": "_prices",
                "type": "uint256[]",
                "internalType": "uint256[]"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setSaleId",
        "type": "function",
        "inputs": [
            {
                "name": "_saleId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setSymbol",
        "type": "function",
        "inputs": [
            {
                "name": "_symbol",
                "type": "string",
                "internalType": "string"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setTokenIdMaxSupply",
        "type": "function",
        "inputs": [
            {
                "name": "_tokenId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "_maxSupply",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "setTreasuryWallet",
        "type": "function",
        "inputs": [
            {
                "name": "_treasuryWallet",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "supplyPerId",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "max",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "total",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "supportsInterface",
        "type": "function",
        "inputs": [
            {
                "name": "interfaceId",
                "type": "bytes4",
                "internalType": "bytes4"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "symbol",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "tierLogicInitialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "tierMint",
        "type": "function",
        "inputs": [
            {
                "name": "to",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "tierNo",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "ids",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "amounts",
                "type": "uint256[]",
                "internalType": "uint256[]"
            },
            {
                "name": "token",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "merkleProof",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
            }
        ],
        "outputs": [],
        "stateMutability": "payable"
    },
    {
        "name": "tiers",
        "type": "function",
        "inputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "start",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "end",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "merkleRoot",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "limitPerWalletPerTier",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "isPublic",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "transferOwnership",
        "type": "function",
        "inputs": [
            {
                "name": "newOwner",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "name": "treasuryInitialized",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "treasuryWallet",
        "type": "function",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "name": "uri",
        "type": "function",
        "inputs": [
            {
                "name": "tokenId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    }
]
})
```

The `data` is always returning ContractFunctionExecutionError. If I call these functions from the contract itself or use something else like Web3 directly, then it works

**Comment by jxom** [comment]
Seems like the issue is that the public RPC URL returns empty data:

```
curl 'https://rpc.sepolia.org' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","id":3,"method":"eth_call","params":[{"data":"0x039af9eb0000000000000000000000000000000000000000000000000000000000000002","to":"0x862afdb5bef06bc673a23e9cb2109d55125c3069"},"latest"]}' \
  --compressed
```

I tried again with Alchemy/Infura and it returned with the correct data, so I'd recommend to use an RPC Provider like Alchemy or Infura and not rely on a Public RPC.

**Comment by pablohpsilva-forjnetwork** [comment]
🤦🏻‍♂️ thank you @jxom
